# Generated by Django 5.1.4 on 2024-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_flowdata_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdata',
            name='firewall_status',
            field=models.IntegerField(default=0),
        ),
    ]
